/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

const SDD_DOCS_INSTRUCTIONS = `Create company SDD documents for completed code changes.

Use this when the implementation already exists and the repository still needs the company SDD directory configured by the enterprise SDD settings.

**Input**: The user's request should include a req id plus a change name (kebab-case) OR a short description of the completed fix/change.

Recognize req id when provided as the first token (e.g., \`DSH-618\`) or in compact forms such as \`req:DSH-618\`, \`req=DSH-618\`, \`需求号是DSH-618\`, \`需求ID是DSH-618\`, or legacy Jira forms such as \`jira号是DSH-618\`. Do not infer req id from git branches or URLs.

**Steps**

1. **Collect req id and completed-change intent**

   If no req id is present, use the **AskUserQuestion tool** to ask:
   > "What requirement id should these SDD docs use? Provide the id only, like DSH-618. If these docs should not include one, say none."

   If no clear change intent is provided, use the **AskUserQuestion tool** (open-ended, no preset options) to ask:
   > "What completed change should these SDD docs describe?"

   From the remaining description after removing req id text, derive a kebab-case name (e.g., "fix login captcha error" -> \`fix-login-captcha-error\`).

   **IMPORTANT**: Do NOT proceed without enough intent to name the change. If the req id is unavailable, proceed only after the user confirms it should be omitted.

2. **Inspect the completed code changes**

   Run:
   \`\`\`bash
   git status --short
   git diff --stat
   git diff
   \`\`\`

   Use the diff plus the user's description to understand:
   - The bug or change being addressed
   - The behavior that changed
   - The files, modules, APIs, data, or UI affected
   - Tests or verification already added or needed

   If there is no usable current diff, ask the user for a commit range, changed files, or a short implementation summary, then inspect the provided source before writing docs.

3. **Create the company SDD directory**

   Run:
   \`\`\`bash
   openspec sdd docs --req-id "<req-id>" --name "<name>"
   \`\`\`
   If the user confirmed there is no req id, use \`--omit-req-id\` instead of \`--req-id\`.

   Use the printed \`SDD docs directory:\` path as the target directory.

4. **Write standard spec-driven artifacts**

   Write these files under the created SDD docs directory:
   - \`proposal.md\`
   - \`design.md\`
   - \`tasks.md\`
   - \`specs/<capability>/spec.md\`

   Use the standard \`spec-driven\` artifact structure:

   \`proposal.md\`:
   - \`## Why\`
   - \`## What Changes\`
   - \`## Capabilities\`
   - \`### New Capabilities\`
   - \`### Modified Capabilities\`
   - \`## Impact\`

   \`design.md\`:
   - \`## Context\`
   - \`## Goals / Non-Goals\`
   - \`## Decisions\`
   - \`## Risks / Trade-offs\`
   - Write as a design document, not as a code review or implementation audit
   - Describe intended architecture, decisions, constraints, and trade-offs at a conceptual level
   - Do NOT quote, paste, or closely paraphrase source code, conditions, function signatures, variable names, error strings, or line-level implementation details
   - Do NOT use review-style wording such as "the existing code does/does not", "the diff shows", "the implementation already", "the code currently", or "we observed in code"
   - Risk analysis must describe product, architecture, operations, compatibility, security, performance, or rollout risks in plain language, with mitigations; it must not cite code snippets or exact implementation text

   \`tasks.md\`:
   - Use standard checkbox tasks grouped under numbered \`##\` headings
   - Because this command documents completed work, mark generated tasks as complete with \`- [x]\`
   - Keep tasks aligned with the actual diff

   \`specs/<capability>/spec.md\`:
   - Prefer an existing capability name from \`openspec/specs/<capability>\` when the diff clearly modifies existing behavior
   - If no existing capability matches, use the derived change name as the capability
   - Write valid delta spec content with \`## ADDED Requirements\` or \`## MODIFIED Requirements\`
   - Every requirement MUST have at least one \`#### Scenario:\` using WHEN/THEN bullets

5. **Check the generated files**

   Confirm every expected file exists. Re-read the files and verify they follow the standard spec-driven templates and requirement/scenario syntax:
   - \`.openspec.yaml\` has \`schema\`, \`created\`, and \`sdd\` only
   - \`proposal.md\`, \`design.md\`, and \`tasks.md\` use the standard headings above
   - \`tasks.md\` uses \`- [x]\` checkbox lines
   - \`specs/<capability>/spec.md\` uses \`## ADDED Requirements\` or \`## MODIFIED Requirements\`
   - Every requirement includes at least one \`#### Scenario:\` with WHEN/THEN bullets

**Output**

Summarize:
- Req id, or note that it was intentionally omitted
- Created company SDD directory
- Capability spec path
- Source used for the docs (current diff, commit range, or user-provided summary)
- Checks performed

**Guardrails**
- Do not create \`openspec/changes/<name>\` for this workflow
- Do not add nonstandard metadata fields to \`.openspec.yaml\`
- Do not modify git history or file timestamps
- Keep generated docs consistent with the actual completed code changes`;

export function getSddDocsSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-sdd-docs',
    description: 'Create company SDD documents for completed code changes using the current git diff and standard spec-driven artifact format.',
    instructions: SDD_DOCS_INSTRUCTIONS,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxSddDocsCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: SDD Docs',
    description: 'Create company SDD docs for completed code changes',
    category: 'Workflow',
    tags: ['workflow', 'sdd', 'docs'],
    content: SDD_DOCS_INSTRUCTIONS,
  };
}
